---
- name: validate sshd configuration
  ansible.builtin.command:
    cmd: /usr/sbin/sshd -t
  changed_when: false
  listen: restart sshd

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  listen: restart sshd

- name: reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  listen: reload firewalld